// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOuanO7y12uohdg_xWAbyP2iZl88Y4BRo',
    appId: '1:489536134509:web:8fecbbf48e84988ff20e64',
    messagingSenderId: '489536134509',
    projectId: 'anonymous-chat-ed611',
    authDomain: 'anonymous-chat-ed611.firebaseapp.com',
    databaseURL: 'https://anonymous-chat-ed611.firebaseio.com',
    storageBucket: 'anonymous-chat-ed611.appspot.com',
    measurementId: 'G-2KL90QXZW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuHTTC5--RBhB2how564Dt0PotcSMAFsg',
    appId: '1:489536134509:android:15bbbdf76eee3985f20e64',
    messagingSenderId: '489536134509',
    projectId: 'anonymous-chat-ed611',
    databaseURL: 'https://anonymous-chat-ed611.firebaseio.com',
    storageBucket: 'anonymous-chat-ed611.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFSB9gBgFRFF1Jl33lc07bGjz1ThcvdRw',
    appId: '1:489536134509:ios:17da7ba589d3f2aef20e64',
    messagingSenderId: '489536134509',
    projectId: 'anonymous-chat-ed611',
    databaseURL: 'https://anonymous-chat-ed611.firebaseio.com',
    storageBucket: 'anonymous-chat-ed611.appspot.com',
    iosBundleId: 'com.rezuanulfahim.anonymousChat',
  );
}
